name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      requestId:
        description: 'Cherrypick Request ID'
        required: true
        type: string
      commitIds:
        description: 'commits to be cherrypicked'
        required: true
        type: string

jobs:
  Cherrypick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cherrypick commits
        id: cherrypick
        run: |
          BRANCH_NAME=${{ github.ref }}
          BRANCH_NAME=${BRANCH_NAME##*/}
          git config --global user.email "praveenganesh7@gmail.com"
          git config --global user.name "Praveen Kumar"
          if [ "${{ github.event.inputs.commitIds }}" != "skip" ]; then
            COMMIT_SHAS="${{ github.event.inputs.commitIds }}"
            IFS=',' read -r -a COMMIT_ARRAY <<< "$COMMIT_SHAS"
  
            for COMMIT in "${COMMIT_ARRAY[@]}"; do
              echo "Cherry-picking commit: $COMMIT"
              git cherry-pick $COMMIT || exit 1
            done
            
            git status
            echo "cherrypick finished"
            git push origin $BRANCH_NAME
            echo "pushed changes to $BRANCH_NAME"
          fi
          

      # - name: Trigger API call on failure
      #   if: failure()
      #   run: |
      #     REQ_ID="${{ github.event.inputs.requestId }}"
      #     echo "req id is $REQ_ID"
      #     curl -X PATCH "http://cherrypicker.mvp-by-praveen.click:4000/api/requests-manager/requests/$REQ_ID/status" \
      #     -H "Content-Type: application/json" \
      #     -d '{"isSuccess": false, pickedWithConflicts: false}'

      # - name: Trigger API call on success
      #   if: success()
      #   run: |
      #     REQ_ID="${{ github.event.inputs.requestId }}"
      #     echo "req id is $REQ_ID"
      #      # Construct JSON payload
      #     if [ "${{ github.event.inputs.commitIds }}" != "skip" ]; then
      #       JSON_PAYLOAD='{"isSuccess": true, "pickedWithConflicts": true}'
      #     else
      #       JSON_PAYLOAD='{"isSuccess": true, "pickedWithConflicts": false}'
      #     fi
      #     curl -X PATCH "http://cherrypicker.mvp-by-praveen.click:4000/api/requests-manager/requests/$REQ_ID/status" \
      #     -H "Content-Type: application/json" \
      #     -d "$JSON_PAYLOAD"
