name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      requestId:
        description: 'Cherrypick Request ID'
        required: true
        type: string
      commits:
        description: 'commits to be cherrypicked'
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check input number
        id: cherrypick
        run: |
          BRANCH_NAME=${{ github.ref }}
          BRANCH_NAME=${BRANCH_NAME##*/}
          COMMIT_SHA=${{ github.event.input.commits }}
          echo "commit is $COMMIT_SHA"
          git cherry-pick $COMMIT_SHA
          git status
          echo "cherrypick finished"
          git push origin $BRANCH_NAME
          echo "pushed changes to $BRANCH_NAME"

      - name: Trigger API call on failure
        if: failure()
        run: echo "updating reuqest ${{ github.event.inputs.requestId }} to conflict"

      - name: Trigger API call on success
        if: success()
        run: echo "updating reuqest ${{ github.event.inputs.requestId }} to success"
