name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'ID for the process'
        required: true
        type: string
      name:
        description: 'Name for the process'
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check input number
        id: check_input
        run: |
          if [ "${{ github.event.inputs.id }}" -eq 1 ]; then
            echo "Input is 1, throwing error..."
            exit 1
          else
            echo "Input is not 1, proceeding with success."
          fi

      - name: Trigger API call on failure
        if: failure()
        run: echo "Input is 1, throwing error..."

      - name: Trigger API call on success
        if: success()
        run: echo "Input is not 1, proceeding with success."
