name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      requestId:
        description: 'Cherrypick Request ID'
        required: true
        type: string
      commits:
        description: 'commits to be cherrypicked'
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check input number
        id: cherrypick
        run: |
          BRANCH_NAME=${{ github.ref }}
          BRANCH_NAME=${BRANCH_NAME##*/}
          git config --global user.email "praveenganesh7@gmail.com"
          git config --global user.name "Praveen Kumar"
          COMMIT_SHAS="${{ github.event.inputs.commits }}"
          IFS=',' read -r -a COMMIT_ARRAY <<< "$COMMIT_SHAS"

          for COMMIT in "${COMMIT_ARRAY[@]}"; do
            echo "Cherry-picking commit: $COMMIT"
            git cherry-pick $COMMIT || exit 1
          done
          git status
          echo "cherrypick finished"
          git push origin $BRANCH_NAME
          echo "pushed changes to $BRANCH_NAME"

      - name: Trigger API call on failure
        if: failure()
        run: |
          REQ_ID="${{ github.event.inputs.commits }}"
          echo "req id is $REQ_ID"
          curl -X PATCH "http://65.2.169.224:3000/api/requests-manager/requests/$REQ_ID/status" \
          -H "Content-Type: application/json" \
          -d '{"isSuccess": false}'

      - name: Trigger API call on success
        if: success()
        run: |
          REQ_ID="${{ github.event.inputs.commits }}"
          echo "req id is $REQ_ID"
          curl -X PATCH "http://65.2.169.224:3000/api/requests-manager/requests/$REQ_ID/status" \
          -H "Content-Type: application/json" \
          -d '{"isSuccess": true}'
