name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      requestId:
        description: 'Cherrypick Request ID'
        required: true
        type: string
      commits:
        description: 'commits to be cherrypicked'
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check input number
        id: cherrypick
        run: |
          echo "${{ github.event.inputs.commits }}"
          echo "${{ github.event.inputs.requestId }}"
          for i in $(echo ${{ github.event.input.commits }} | sed "s/,/ /g"
          do
            echo $i
          done
          git log

      - name: Trigger API call on failure
        if: failure()
        run: echo "Input is 1, throwing error..."

      - name: Trigger API call on success
        if: success()
        run: echo "Input is not 1, proceeding with success."
